version: '3.8'

services:
  # Database
  database:
    container_name: travel-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel
      MYSQL_USER: travel
      MYSQL_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  # Phone Support
  phone-support:
    container_name: travel-app
    ports:
      - '80:80'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - .:/var/www
